### ISSUE TITLE
Добавить блок "Возможные друзья"

### ISSUE THREAD

**Issue by satonin12** [alex-altay/cleanVk#1]
Добавить блок "Возможные друзья" справа в новостной ленте

class="vkuiGroup__inner"

![изображение](https://user-images.githubusercontent.com/24912294/220173379-18fe9424-29db-4f4d-b61f-0fbd61323c4d.png)

**Comment by alex-altay** [comment]
Привет
По такому селектору это сделать нельзя, он используется в других местах и делать отдельный выключатель для этого блока, который только на странице Друзья, тоже как мне показалось - излишне.

Поэтому я сделал вот как: теперь включение чекбокса 'Блок "Возможно, вы знакомы"' будет скрывать и этот блок.

Обновления скоро станут доступны в Хроме и Файрфоксе, пользуйся
